services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - mongodb:/app/db

  node:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongodb

volumes:
  mongodb: {}
